### ISSUE TITLE
Bare & in href URL always produces parser error

### ISSUE THREAD

**Issue by mundschenk-at** [Masterminds/html5-php#124]
If I understand the current spec (or rather: the commentary on said spec) correctly, a bare `&` in a URL in a `href` attribute should only produce a parser error if the text fragment following the `&` is the name of an entity.

Currently (2.x branch), `<a href="foobar.at?a=b&c=d">bla</a>` results in a parser error `Line 1, Col 51: No match in entity table for 'c'`. Should that really be the case?

**Comment by goetas** [comment]
From my understanding of the specs, & should be always encoded.

But what happens in reality is that a huge part of devs don't, so browsers
have adopted a "think positive" approach, essentially they allow & almost
everywhere, but if the characters after it match an entity, then the entity
is used instead.

On 18 Dec 2016 2:49 pm, "Der Mundschenk & Compagnie" <
notifications@github.com> wrote:

If I understand the current spec (or rather: the commentary on said spec)
correctly, a bare & in an URL in a href attribute should only produce a
parser error if the text fragment following the & is the name of an entity.

Currently (2.x branch), <a href="foobar.at?a=b&c=d">bla</a> results in a
parser error Line 1, Col 51: No match in entity table for 'c'. Should that
really be the case?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Masterminds/html5-php/issues/124>, or mute the thread

**Comment by mundschenk-at** [comment]
The [Nu Html Checker people think this is no longer true](https://github.com/validator/validator/issues/293).

**Comment by mundschenk-at** [comment]
I've found the relevant part of the spec [§ 8.2.4.72. Character reference state](https://www.w3.org/TR/html52/syntax.html#character-reference-state):

Consume the maximum number of characters possible, with the consumed characters matching one of the identifiers in the first column of the §8.5 Named character references table (in a case-sensitive manner). Append each character to the temporary buffer when it’s consumed.

If no match can be made and the temporary buffer consists of a U+0026 AMPERSAND character (&) followed by a sequence of one or more alphanumeric ASCII characters and a U+003B SEMICOLON character (;), then this is a parse error.

If no match can be made, switch to the character reference end state.

**If the character reference was consumed as part of an attribute (return state is either attribute value (double-quoted) state, attribute value (single-quoted) state or attribute value (unquoted) state), and the last character matched is not a U+003B SEMICOLON character (;), and the next input character is either a U+003D EQUALS SIGN character (=) or an alphanumeric ASCII character, then, for historical reasons, switch to the character reference end state.**

**Comment by goetas** [comment]
possible solution available in https://github.com/Masterminds/html5-php/pull/134, feedback is welcome

**Comment by mundschenk-at** [comment]
Code looks good to me, though I don't have a more elaborate test case than the minimal one given earlier. (I encountered this in the wild, but I didn't keep notes on the orginal HTML.)
