### ISSUE TITLE
Why not using \SplFileObject or \php_stream_filter

### ISSUE THREAD

**Issue by sa-tasche** [Masterminds/html5-php#86]
Is there a good reason why we doesn't use \SplFileObject or \php_stream_filter?
It could probably make the parser less complex; perhaps starting from the next major update.

What's your thoughts?

**Comment by technosophos** [comment]
You mean instead of doing the tokenizing the way we are? I had looked at using php_stream_filter, and actually had planned on using it. But I started with plain string processing and then never actually went back to working on streams/files instead.

For background, when we first started the parser, we were most interested in parsing strings of HTML5, not necessarily files. At this point, we really should be thinking more in terms of streams than strings. So I'm sure that if you had time to put together a pull request, we'd all be very happy.

**Comment by mattfarina** [comment]
When I originally wrote the file input stream it was the lowest barrier to entry to make it work. On day one I knew we needed something better but updating that to use something like `SplFileObject` fell into the unimplemented features. I'd love to see a pull request to do something better.

**Comment by goetas** [comment]
As of https://github.com/Masterminds/html5-php/pull/146, the input stream has been deprecated. Using raw php strings allowed to double performance
